### ISSUE TITLE
Is it possible to build a dynamic list of targets with Earthly

### ISSUE THREAD

**Issue by mhvelplund** [earthly/earthly#920] opened 2021-04-09 20:14 UTC
I've been considering the [Earthly](https://docs.earthly.dev/) build automation tool as a replacement for Make in my project. I have a mono repo with a root Makefile, that has a target that scans for subfolders with Makefiles, and builds those with `make -C some_subfolder`.

Looking at the documentation for Eartly, the only way I can see to support those builds is to make a static lists of subfolders, and then build them using the example from the [mono repo documentation](https://docs.earthly.dev/examples/other-earthfile-examples/monorepo), like

```docker
FROM alpine:3.13

all:
    BUILD ./some_subfolder+all
    BUILD ./another_folder+all
```

I've been through the rest of the guides, and I can't see any way to make that list of build instructions dynamic, without writing a wrapper script to run Earthly. Has anyone else had this issue and come up with a solution?

**Comment by vladaionescu** [comment] 2021-04-09 20:20
Hi @mhvelplund - it sounds like you need a `FOR ... IN ...` as described here: https://github.com/earthly/earthly/issues/779?

**Comment by mhvelplund** [comment] 2021-04-09 20:51
> Hi @mhvelplund - it sounds like you need a `FOR ... IN ...` as described here: #779?

Yes!

I was looking at the possibility of making my own for loop with a recursive user command and and if statements, but it feels like working against the grain of Earthly somehow ...

**Comment by mhvelplund** [comment] 2021-04-09 21:35
This works, but it makes me feel unclean :)

```
main:
    DO +LOOP --command=ECHO --list="a b c"
    RUN echo DONE

LOOP:
    COMMAND
    ARG command
    ARG list
    RUN [ ! -z "$list" ] && echo "$list" > /tmp/remainder || true
    RUN cat /tmp/remainder | cut -f1 -d" " > /tmp/item
    IF [ "$(cat /tmp/item)" == "$(cat /tmp/remainder)" ]
        RUN rm /tmp/remainder
    ELSE
        RUN cat /tmp/remainder | cut -f2- -d" " > /tmp/remainder_ && mv /tmp/remainder_ /tmp/remainder
    END
    DO +$command
    IF [ -f /tmp/remainder ]
        DO +LOOP --command=$command
    END

ECHO:
    COMMAND
    RUN cat /tmp/item
```

**Comment by vladaionescu** [comment] 2021-04-10 02:08
Hah! Yeah, you shouldn't have to do recursion for something so simple :D

**Comment by vladaionescu** [comment] 2021-04-10 02:08
I'll close as duplicate. Feel free to leave any feedback on that other issue.

**Comment by vladaionescu** [comment] 2021-04-10 02:09
Duplicate of #779

**Closed by vladaionescu** 2021-04-10 02:08 UTC
