### ISSUE TITLE
investigate having renovate update the dind versions automatically

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3781] opened 2024-02-05 23:37 UTC
We have some tags under

```
dind-alpine:
    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=alpine --OS_VERSION=3.19 --DOCKER_VERSION=25.0.2-r0

dind-ubuntu-20.04:
    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=ubuntu --OS_VERSION=20.04 --DOCKER_VERSION=5:24.0.5-1~ubuntu.20.04~focal

dind-ubuntu-23.04:
    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=ubuntu --OS_VERSION=23.04 --DOCKER_VERSION=5:24.0.5-1~ubuntu.23.04~lunar
```

which need to be kept up to date.

maybe renovate can help us with this task?

**Comment by idodod** [comment] 2024-04-02 18:55
Duplicate of https://github.com/earthly/earthly/issues/3786

**Closed by idodod** 2024-04-02 18:55 UTC
