### ISSUE TITLE
Remote cache fails when using `--wait-block`

### ISSUE THREAD

**Issue by serverwentdown** [earthly/earthly#2630] opened 2023-01-30 10:02 UTC
```
EARTHLY_ADDITIONAL_BUILDKIT_CONFIG="[registry.\"172.17.0.1:5000\"]
  http = true"
```

```earthfile
VERSION --shell-out-anywhere --wait-block 0.6

tools-wget:
        FROM debian:buster-slim
        ARG DEBIAN_FRONTEND=noninteractive
        RUN apt-get update \
                && apt-get install -y \
                        wget \
                && rm -rf /var/lib/apt/lists/*
        SAVE IMAGE --push 172.17.0.1:5000/tools-wget
```

```sh
docker run \
                --rm --detach \
                --publish 5000:5000 \
                --name inline-cache-broken-test-registry \
                registry:2
```

```sh
earthly --ci --push +tools-wget
# successfully pushed
earthly prune
# clear cache
earthly --ci +tools-wget
# will build from scratch
```

Now, remove the `--wait-block` and run the commands again. It succeeds

**Comment by vladaionescu** [comment] 2023-01-30 19:05
I *think* that this is a duplicate of a known issue. @alexcb to confirm.

**Comment by alexcb** [comment] 2023-01-30 20:04
This is a duplicate of #2178

That ticket has an explicit `WAIT` / `END`; however, internally earthly wraps the initial target referenced on the command line with an implicit `WAIT` block, which triggers the same code path that contains the bug.

**Closed by alexcb** 2023-01-30 20:04 UTC
