### ISSUE TITLE
bug: docker authentication expires after a few hours causing 401 errors while building

### ISSUE THREAD

**Issue by tchupp** [earthly/earthly#890] opened 2021-03-24 18:36 UTC
I have an Earthfile that extends a private image. After a few hours of using earthly, I start getting 401 errors. I'm still able to pull the image with docker pull, and running docker login doesn't have any effect.

I am able to get it working again by restarting the earthly container manually, or by changing the arguments I run with.

```
$ earthly -i +test
     buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
     quay.io/<org>/<image>:<tag> | --> Load metadata linux/amd64
     quay.io/<org>/<image>:<tag> | WARN: (Load metadata linux/amd64) unexpected status code [manifests ci]: 401 UNAUTHORIZED
Error: unexpected status code [manifests ci]: 401 UNAUTHORIZED

$ docker login quay.io                                              
Authenticating with existing credentials...
Login Succeeded

$ docker pull quay.io/<org>/<image>:<tag>
<tag>: Pulling from <org>/<image>
Digest: sha256:fcacc41495f6a7655032299d0ea83de0a9e577b64eaaaab8e4bf53a8f81bddb3
Status: Image is up to date for quay.io/<org>/<image>:<tag>
quay.io/<org>/<image>:<tag>

$ earthly -i +test
     buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
     quay.io/<org>/<image>:<tag> | --> Load metadata linux/amd64
     quay.io/<org>/<image>:<tag> | WARN: (Load metadata linux/amd64) unexpected status code [manifests ci]: 401 UNAUTHORIZED
Error: unexpected status code [manifests ci]: 401 UNAUTHORIZED

$ earthly +test
                   buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
                   buildkitd | Settings do not match. Restarting buildkit daemon with updated settings...
                   buildkitd | ...Done
 quay.io/<org>/<image>:<tag> | --> Load metadata linux/amd64
                       +base | --> FROM quay.io/<org>/<image>:<tag>
                     context | --> local context .
                       +base | [██████████] resolve quay.io/<org>/<image>:<tag>@sha256:fcacc41495f6a7655032299d0ea83de0a9e577b64eaaaab8e4bf53a8f81bddb3 ... 100%
                     context | [██████████] transferring .: ... 100%
```

[This documentation](https://docs.earthly.dev/guides/auth#docker-authentication) suggests that Earthly should be able to inherited from the host. [This page](https://docs.earthly.dev/guides/configuring-registries) doesn't contain anything special for quay.

Is it possible I'm missing something? Or is this unintended behavior?

**Comment by dchw** [comment] 2021-03-24 20:07
Author of the repository authentication docs here!

It looks like the Quay.io credentials are expiring, would be my guess. Are you using a credential helper at all? For testing, I've created a private repo on Quay and started testing there.

> or by changing the arguments I run with.

 What do you mean here? The arguments to Earthly?

Hopefully we can figure this out quick and amend out documentation!

**Comment by tchupp** [comment] 2021-03-25 05:03
I'm not using a credentials helper, I just logged in locally with `docker login quay.io` a few months ago and I don't have a problem when using docker directly.

> Reading your example, removing the -i fixed it for you, I believe?

Yes! That's correct.

**Comment by dchw** [comment] 2021-03-25 15:32
Interesting. I let my setup mellow overnight, and it still seemed to work this morning. I was; however building with `--no-cache` each time to ensure it went through everything. I'll let it sit more this morning and try without.

I've also been watching the auth hash: `cat /home/dchw/.docker/config.json | jq -r .auths.\"quay.io\".auth | base64 -d`, to see if it updates at all over this span, and it has not. Narrowing it down...

**Comment by tchupp** [comment] 2021-03-25 17:20
It certainly is a hassle trying to debug this one, since it takes a few hours to even see if it pops up again 😂

**Comment by tchupp** [comment] 2021-03-29 17:50
I've just encountered this again today after coming back from lunch. Here is my docker config:
```
$ cat ~/.docker/config.json                                       
{
        "auths": {
                "quay.io": {}
        },
        "credsStore": "desktop",
        "experimental": "disabled",
        "stackOrchestrator": "swarm"
}
```
As far as I can remember, it looked like this before as well.

I'm still able to run `docker pull quay.io/<org>/<earthly base image>` without any errors

**Comment by dchw** [comment] 2021-03-29 18:47
Thanks for the follow up! Rather than trying something, and waiting 4 hours... I am setting up a local repository I can use, that I configured to expire tokens more quickly. I'm still looking at it; sorry for the delay!

**Comment by dchw** [comment] 2021-03-30 17:31
So, I _think_ I got to the bottom of this yesterday. Lets see if I can provide a decent summary. Its one of those bugs thats a confluence of a couple factors - so here it goes:

1. Quay returns the _bare minimum_ in authentication. [See here for details, heading "Token Response Fields"](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token). Notably, this omits the `expires_in` field.
2. Containerd interprets this _missing_ field as an `expires_in` of 0, and notifies Buildkit that this is zero.
3. Buildkit treats an `expires_in` of 0 as "doesn't expire", and dutifully caches the token, to prevent overhead from re-authentication.
4. Additionally, Buildkit cleans up all cached credentials when they haven't been used for more than 10 minutes; including ones from Quay. It checks this every 5 minutes.

So, to reproduce this, you need to execute a target that talks to Quay, at least once every 10-ish minutes for at least an hour (the JWT coming from Quay in my case has an `exp` of 1 hour in the future). I was able to reproduce this error with the following target, and shell command:

**Earthfile:**
```
quay:
    FROM quay.io/dchw/testing
    RUN echo bye > goodbye.txt
```

**Command:**
```
$ watch -n 300 earthly +quay
```

So - this unfortunately means that workarounds are few and far between. Your options are to either:

1. Restart the Buildkit container
2. Wait 10-15 minutes for the GC to clean up the "unused" token
 
We are running this up the flagpole to Buildkit, and hopefully we can get this resolution upstream. Sorry for the inconvenience, I wish it was something I could fix right now on our side!

**Comment by tchupp** [comment] 2021-03-30 19:46
Wow! That's some crazy digging you did!! I really appreciate it 😁 
I see the line
> When omitted, this defaults to 60 seconds.

But you also say
> Containerd interprets this _missing_ field as an `expires_in` of 0, and notifies Buildkit that this is zero.

Is this a bug with buildkit/containerd then?

**Comment by dchw** [comment] 2021-03-30 19:53
> Is this a bug with buildkit/containerd then?

Yep. We need a fix in one of those, somewhere. Exactly the discrepancy that we need to solve or compensate for somewhere.

**Comment by dchw** [comment] 2021-04-02 17:07
I'm not seeing a ton of traction on the bug I opened with buildkit. I made an 9admittedly crude) fix. I'll submit it over there to press the issue a little bit.

**Comment by dchw** [comment] 2021-04-05 15:19
@tchupp Sorry resolving this is taking so long! Just letting you know we haven't forgotten you!

**Comment by tchupp** [comment] 2021-04-07 18:42
I've been following along in the other repos as well! Thank you for the updates 😁

**Comment by dchw** [comment] 2021-04-26 19:16
Finally upstream has updated. I'll be sure to ping back once we pull in upstream buildkit with this change... and this long adventure will be over.

**Comment by dchw** [comment] 2021-04-28 19:53
Integrating the upstream change: https://github.com/earthly/buildkit/pull/40

**Comment by dchw** [comment] 2021-05-11 23:00
With the release (just now) of https://github.com/earthly/earthly/releases/tag/v0.5.11, yes.

**Closed** 2021-05-11 23:00 UTC

**Comment by tchupp** [comment] 2021-05-27 12:42
I forgot to respond here; thank you for taking care of this! We haven't seen this issue in a few days now 😁
