### ISSUE TITLE
$USERPLATFORM breaking change since v0.6.29

### ISSUE THREAD

**Issue by gnuletik** [earthly/earthly#2446] opened 2022-11-24 09:24 UTC
On Mac M1, the `$USERPLATFORM` variable used to show `linux/arm64` but it now shows `darwin/arm64` with the following Earthfile:

```Earthfile
VERSION 0.6
FROM golang:1.19-alpine
WORKDIR /go-workdir

ARG USERPLATFORM

deps:
    RUN go mod download
    SAVE ARTIFACT +deps/pkgmod /go/pkg/mod

build:
    COPY --platform $USERPLATFORM +deps/pkgmod /go/pkg/mod
    COPY main.go .
    RUN go build -o output/example main.go
    ENTRYPOINT ["/go-workdir/example"]
    SAVE IMAGE go-example:latest
```

So, when building with
```
earthly +build
```

The command now fails with:
```
 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

  golang:1.19-alpine | --> Load metadata linux/arm64
  golang:1.19-alpine | darwin/arm64
  golang:1.19-alpine | --> Load metadata darwin/arm64
  golang:1.19-alpine | WARN: The command 'Load metadata darwin/arm64' failed: no match for platform in manifest sha256:d171aa333fb386089206252503bc6ab545072670e0286e3d1bbc644362825c6e: not found
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to solve: Earthfile line 12:4 copy artifact: apply build +deps: earthfile2llb for +deps: Earthfile line 7:0 apply FROM: apply build +base: earthfile2llb for +base: Earthfile line 2:0 apply FROM golang:1.19-alpine: resolve image config for golang:1.19-alpine: no match for platform in manifest sha256:d171aa333fb386089206252503bc6ab545072670e0286e3d1bbc644362825c6e: not found
in		github.com/earthly/earthly/examples/tutorial/go/part1:main+base
in		github.com/earthly/earthly/examples/tutorial/go/part1:main+deps
in		github.com/earthly/earthly/examples/tutorial/go/part1:main+build
```

```
$ earthly --version
earthly version v0.6.30 743687991d227f2f7e2e6ba11a90f443b4f99c67 unknown homebrew-earthly
```

There's the same issue with `v0.6.29` but it works with version`v0.6.28` and below.

Is there any workaround?

**Comment by vladaionescu** [comment] 2022-11-24 16:25
You might want to use NATIVEPLATFORM instead. User platform is supposed to be the platform of the user, while native platform is the platform is the runner.

I'll close this issue as this is working as intended now.

**Comment by vladaionescu** [comment] 2022-11-24 16:26
Oh and if you really want the user platform, you could also use linux/$USERARCH.

**Closed** 2022-11-24 16:27 UTC

**Comment by gnuletik** [comment] 2022-11-24 17:25
`NATIVEPLATFORM` works like a charm! Thanks!

Maybe the [multi platform guide](https://docs.earthly.dev/docs/guides/multi-platform) should be updated to reflect this change?
Also, that could be useful to update the changelog about the breaking change for users coming by.
