### ISSUE TITLE
WITH DOCKER hits cgroup issues on rootless docker daemon

### ISSUE THREAD

**Issue by pbecotte** [earthly/earthly#3689] opened 2024-01-10 13:56 UTC
**What went wrong?**

I am running the following setup-
WSL v2
Ubuntu 22.04.3
Nix Package manager used to install Docker. Docker is running rootless under a user systemd unit.
Earthly 0.7.17 installed from nix

Attempted to run the example from the tutorial

```

hello:
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
    WITH DOCKER --pull hello-world
        RUN docker run hello-world
    END

```

Gets the following error message-

```

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown

```

The buildkit container _does_ have groups mounted at /sys/fs/cgroup. Using the interactive debugger, the build container started by buildkit does not have anything mounted at /sys/fs/cgroup. I was able to verify that if I started the docker daemon as root, the earthly command worked with no further modification. 

```

$ docker logs earthly-buildkitd
starting earthly-buildkit with EARTHLY_GIT_HASH=7b7d8f4abbc7a35034fcd29cfada52d3d25fcff2 BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:c7693ebc3b039d047ed3def2d1bcda90de27876e+build
detected cgroups v2; buildkit/entrypoint.sh running under pid=1 with controllers "cpuset cpu io memory pids" in group 0::/
Autodetecting iptables
Could not find an ip_tables module; falling back to heuristics.
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Detected iptables-legacy by output length (4 >= 4)
BUILDKIT_ROOT_DIR=/tmp/earthly/buildkit
CACHE_SIZE_MB=0
BUILDKIT_MAX_PARALLELISM=20
BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371
EARTHLY_ADDITIONAL_BUILDKIT_CONFIG=
CNI_MTU=1500
OOM_SCORE_ADJ=0
 (oom script)
Detected container architecture is x86_64
time="2024-01-10T13:30:15Z" level=info msg="auto snapshotter: using overlayfs"
time="2024-01-10T13:30:15Z" level=info msg="found worker \"7np0stgpg86epuixvztmv65ve\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:076e78e437fc org.mobyproject.buildkit.worker.network:cni org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386]"
time="2024-01-10T13:30:15Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2024-01-10T13:30:15Z" level=info msg="found 1 workers, default=\"7np0stgpg86epuixvztmv65ve\""
time="2024-01-10T13:30:15Z" level=warning msg="currently, only the default worker can be used."
time="2024-01-10T13:30:15Z" level=info msg="Starting local registry for outputs on port 8371"
time="2024-01-10T13:30:15Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.20.7
time="2024-01-10T13:30:15Z" level=info msg="redis not configured" go.version=go1.20.7
time="2024-01-10T13:30:15Z" level=info msg="Starting upload purge in 55m0s" go.version=go1.20.7
time="2024-01-10T13:30:15Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
time="2024-01-10T13:30:18Z" level=info msg="response completed" go.version=go1.20.7 http.request.host="172.30.0.1:8371" http.request.id=a3c6eb0b-bd1f-4788-b4fb-373a1e5065e1 http.request.method=GET http.request.remoteaddr="172.30.0.2:42460" http.request.uri=/v2/ http.request.useragent="docker/23.0.6 go/go1.20.7 git-commit/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff kernel/5.15.133.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration="522.408µs" http.response.status=200 http.response.written=2
time="2024-01-10T13:30:18Z" level=info msg="response completed" go.version=go1.20.7 http.request.host="172.30.0.1:8371" http.request.id=382902f7-9070-42cc-b272-6c1bd427fe97 http.request.method=HEAD http.request.remoteaddr="172.30.0.2:42472" http.request.uri=/v2/sess-9dlo5swf6om5ep1aoznjvs4us/manifests/img-0 http.request.useragent="docker/23.0.6 go/go1.20.7 git-commit/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff kernel/5.15.133.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype=application/vnd.docker.distribution.manifest.v2+json http.response.duration="809.847µs" http.response.status=200 http.response.written=499
time="2024-01-10T13:30:18Z" level=info msg="response completed" go.version=go1.20.7 http.request.host="172.30.0.1:8371" http.request.id=f82790db-d817-4a41-b1f7-763750233f32 http.request.method=GET http.request.remoteaddr="172.30.0.2:42478" http.request.uri="/v2/sess-9dlo5swf6om5ep1aoznjvs4us/manifests/sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c" http.request.useragent="docker/23.0.6 go/go1.20.7 git-commit/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff kernel/5.15.133.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype=application/vnd.docker.distribution.manifest.v2+json http.response.duration="845.223µs" http.response.status=200 http.response.written=499
time="2024-01-10T13:30:18Z" level=info msg="response completed" go.version=go1.20.7 http.request.host="172.30.0.1:8371" http.request.id=7aeffbef-e8ac-4a09-b57b-56571ad9b8f1 http.request.method=GET http.request.remoteaddr="172.30.0.2:42482" http.request.uri="/v2/sess-9dlo5swf6om5ep1aoznjvs4us/blobs/sha256:092431e22b8fb1950b16b0ed3faa9f9666b20fb974d63e15f62ba521307b1e45" http.request.useragent="docker/23.0.6 go/go1.20.7 git-commit/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff kernel/5.15.133.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype=application/octet-stream http.response.duration=1.491854ms http.response.status=200 http.response.written=566
time="2024-01-10T13:30:18Z" level=info msg="response completed" go.version=go1.20.7 http.request.host="172.30.0.1:8371" http.request.id=bfbce5f2-10ee-4061-aa03-d0f3d96e7370 http.request.method=GET http.request.remoteaddr="172.30.0.2:42480" http.request.uri="/v2/sess-9dlo5swf6om5ep1aoznjvs4us/blobs/sha256:c1ec31eb59444d78df06a974d155e597c894ab4cda84f08294145e845394988e" http.request.useragent="docker/23.0.6 go/go1.20.7 git-commit/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff kernel/5.15.133.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.6 \\(linux\\))" http.response.contenttype=application/octet-stream http.response.duration=2.558571ms http.response.status=200 http.response.written=2459
time="2024-01-10T13:30:27Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/ReadDir returned error: rpc error: code = Unknown desc = process \"/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\\\"/var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f\\\" EARTHLY_DOCKER_LOAD_FILES=\\\"\\\" EARTHLY_IMAGES_WITH_DIGESTS=\\\"hello-world:latest@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c\\\" EARTHLY_START_COMPOSE=\\\"false\\\" EARTHLY_COMPOSE_FILES=\\\"\\\" EARTHLY_COMPOSE_SERVICES=\\\"\\\" PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'docker run hello-world'\" did not complete successfully: exit code: 125" revision=c7693ebc3b039d047ed3def2d1bcda90de27876e version=v0.7.17
time="2024-01-10T13:30:28Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = Earthfile line 6:8 with docker run: unlazy force execution: process \"/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\\\"/var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f\\\" EARTHLY_DOCKER_LOAD_FILES=\\\"\\\" EARTHLY_IMAGES_WITH_DIGESTS=\\\"hello-world:latest@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c\\\" EARTHLY_START_COMPOSE=\\\"false\\\" EARTHLY_COMPOSE_FILES=\\\"\\\" EARTHLY_COMPOSE_SERVICES=\\\"\\\" PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'docker run hello-world'\" did not complete successfully: exit code: 125\nin\t\tgithub.com/pbecotte/terraform-provider-jenkins:main+hello" revision=c7693ebc3b039d047ed3def2d1bcda90de27876e version=v0.7.17
```

I have fiddled with settings like the 'userns' and 'cgroupns` on the buildkit daemon. The error messages above are with cgroupsv2 enabled in the container, as that was one of the things I tried (but fundamentally same error message when I was on the out-of-the-box cgroup setup).

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.11.2)
  compose: Docker Compose (Docker Inc., 2.21.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 11
 Server Version: 20.10.25
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: v1.7.5
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 23.47GiB
 Name: DESKTOP-0CCNQMJ
 ID: Z6TG:VSKO:NFCQ:XHCZ:TXDC:QUWD:5DDE:NGB4:3U2W:QFYO:OZRC:IXKB
 Docker Root Dir: /home/pbecotte/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Full logs

```
$ earthly -P --verbose +hello
            frontend | Running command: docker info
            frontend | Running command: docker info --format={{.SecurityOptions}}
            frontend | Running command: docker info --format={{.DockerRootDir}}
            frontend | docker-shell frontend initialized.
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

            frontend | Running command: docker container inspect earthly-buildkitd
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
            frontend | Running command: docker container inspect earthly-buildkitd
            frontend | Running command: docker image inspect docker.io/earthly/buildkitd:v0.7.17
           buildkitd | Comparing running container "earthly-buildkitd" image ("sha256:44c52073237d9d34935fe4b6aa4216b1be82023f30eb7b3a7f1b9407c7cd8682") with available image "docker.io/earthly/buildkitd:v0.7.17" ("sha256:44c52073237d9d34935fe4b6aa4216b1be82023f30eb7b3a7f1b9407c7cd8682")
            frontend | Running command: docker container inspect earthly-buildkitd
           buildkitd | Settings hashes match ("e9fe7910efadcc66"), no restart required
           buildkitd | Version github.com/earthly/buildkit v0.7.17 c7693ebc3b039d047ed3def2d1bcda90de27876e
           buildkitd | Platforms: linux/amd64 (native) linux/amd64/v2 linux/amd64/v3 linux/386
           buildkitd | Utilization: 0 other builds, 0/20 op load
           buildkitd | GC stats: 430 MB cache, avg GC duration 0s, all-time GC duration 0s, last GC duration 0s, last cleared 0 B

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

Logbus: setting organization "" and project "" at 2024-01-10T08:53:40.988481542-05:00
e/dind:alpine-3.18-docker-23.0.6-r4 | --> Load metadata earthly/dind:alpine-3.18-docker-23.0.6-r4 linux/amd64
e/dind:alpine-3.18-docker-23.0.6-r4 | Completed in 423.492495ms
         hello-world | --> Load metadata hello-world linux/amd64
         hello-world | Completed in 195.405803ms
         hello-world | --> DOCKER PULL hello-world
         hello-world | [          ]   0% resolve docker.io/library/hello-world:latest@sha256:ac69084025c660510933cca701f615283cdbb3[----------] 100% resolve docker.io/library/hello-world:latest@sha256:ac69084025c660510933cca701f615283cdbb3aa0963188770b54c31c8962493
         hello-world | Completed in 37.720884ms
         hello-world | Completed in 33.683µs
              output | --> exporting outputs
              output | [----------] 100% exporting layers
              output | [          ]   0% exporting manifest sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c[----------] 100% exporting manifest sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c
              output | [          ]   0% exporting config sha256:092431e22b8fb1950b16b0ed3faa9f9666b20fb974d63e15f62ba521307b1e45  [----------] 100% exporting config sha256:092431e22b8fb1950b16b0ed3faa9f9666b20fb974d63e15f62ba521307b1e45
              output | [          ]   0% transferring docker.io/library/hello-world:latest
              +hello | --> FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
              +hello | [          ]   0% resolve docker.io/earthly/dind:alpine-3.18-docker-23.0.6-r4@sha256:05ef9c5f3e0adb98d8d00cc[----------] 100% resolve docker.io/earthly/dind:alpine-3.18-docker-23.0.6-r4@sha256:05ef9c5f3e0adb98d8d00cc8efb552ccc8d23e641da6fcd0f315b017832c6584
              +hello | Completed in 38.150358ms
              +hello | *cached* --> WITH DOCKER (install deps)
              +hello | Completed in 44.483µs
              +hello | --> WITH DOCKER RUN --privileged docker run hello-world
              +hello | Starting dockerd with data root /var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f/tmp.foMDbL
              +hello | Loading images from BuildKit via embedded registry...
              +hello | Pulling 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0 and retagging as hello-world:latest
              +hello | img-0: Pulling from sess-mr3vuapke2rli0wa12uk4x1wa
              +hello | c1ec31eb5944: Pulling fs layer
              +hello | c1ec31eb5944: Verifying Checksum
              +hello | c1ec31eb5944: Download complete
              +hello | c1ec31eb5944: Pull complete
              +hello | Digest: sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c
              +hello | Status: Downloaded newer image for 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello | 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello | Untagged: 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello | Untagged: 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c
              +hello | ...done
              +hello | docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown.
              +hello | time="2024-01-10T13:53:43Z" level=error msg="error waiting for container: "
              +hello | ERROR Earthfile line 6:8
              +hello |       The command
              +hello |           WITH DOCKER RUN --privileged docker run hello-world
              +hello |       did not complete successfully. Exit code 125
              +hello | Overriding args used:
              +hello | Completed in 2.793527309s
earthfile2llb immediate error: Earthfile line 6:8 with docker run: unlazy force execution: process "/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\"/var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f\" EARTHLY_DOCKER_LOAD_FILES=\"\" EARTHLY_IMAGES_WITH_DIGESTS=\"hello-world:latest@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c\" EARTHLY_START_COMPOSE=\"false\" EARTHLY_COMPOSE_FILES=\"\" EARTHLY_COMPOSE_SERVICES=\"\" PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'docker run hello-world'" did not complete successfully: exit code: 125
in              github.com/pbecotte/terraform-provider-jenkins:main+hello
earthfile2llb group error: <nil>
              output | [----------] 100% transferring docker.io/library/hello-world:latest
              output | Completed in 2.904098972s

============================= ❌ FAILURE [Build 🔧] ==============================

Repeating the output of the command that caused the failure
              +hello *failed* | --> WITH DOCKER RUN --privileged docker run hello-world
              +hello *failed* | Starting dockerd with data root /var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f/tmp.foMDbL
              +hello *failed* | Loading images from BuildKit via embedded registry...
              +hello *failed* | Pulling 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0 and retagging as hello-world:latest
              +hello *failed* | img-0: Pulling from sess-mr3vuapke2rli0wa12uk4x1wa
              +hello *failed* | c1ec31eb5944: Pulling fs layer
              +hello *failed* | c1ec31eb5944: Verifying Checksum
              +hello *failed* | c1ec31eb5944: Download complete
              +hello *failed* | c1ec31eb5944: Pull complete
              +hello *failed* | Digest: sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c
              +hello *failed* | Status: Downloaded newer image for 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello *failed* | 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello *failed* | Untagged: 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa:img-0
              +hello *failed* | Untagged: 172.30.0.1:8371/sess-mr3vuapke2rli0wa12uk4x1wa@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c
              +hello *failed* | ...done
              +hello *failed* | docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: no cgroup mount found in mountinfo: unknown.
              +hello *failed* | time="2024-01-10T13:53:43Z" level=error msg="error waiting for container: "
              +hello *failed* | ERROR Earthfile line 6:8
              +hello *failed* |       The command
              +hello *failed* |           WITH DOCKER RUN --privileged docker run hello-world
              +hello *failed* |       did not complete successfully. Exit code 125
              +hello *failed* | Overriding args used:
Summary of timing information
Note that the times do not include the expansion of commands like BUILD, FROM, COPY (artifact).
              output | () 2.904098972s
              +hello | () 2.83172215s
e/dind:alpine-3.18-docker-23.0.6-r4 | () 423.492495ms
         hello-world | () 233.16037ms
===============================================================
Total           6.392473987s
Total (real)    3.79635462s
🛰️ Reuse cache between CI runs with Earthly Satellites! 2-20X faster than without cache. Generous free tier https://cloud.earthly.dev
Error: build target: build main: failed to solve: Earthfile line 6:8 with docker run: unlazy force execution: process "/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\"/var/earthly/dind/d957cb3505beac2938e377768ab16f7ceffb12c5fd2942dcf1d8cbfc79b6941f\" EARTHLY_DOCKER_LOAD_FILES=\"\" EARTHLY_IMAGES_WITH_DIGESTS=\"hello-world:latest@sha256:6ed8be42d90c6bb6afd4196b566a860e513f4f88a6be177e01f48f584aaf317c\" EARTHLY_START_COMPOSE=\"false\" EARTHLY_COMPOSE_FILES=\"\" EARTHLY_COMPOSE_SERVICES=\"\" PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'docker run hello-world'" did not complete successfully: exit code: 125
in              github.com/pbecotte/terraform-provider-jenkins:main+hello
```

**Comment by alexcb** [comment] 2024-04-12 17:06
This feels like a duplicate of #1144, which points out that it's not currently possible to use the `WITH DOCKER` command when earthly is started using rootless docker.

**Closed by alexcb** 2024-04-12 17:06 UTC
Labels: type:bug
