### ISSUE TITLE
Earthly on WSL2 fails with "is not absolute" Git path error when checkout on Windows 10

### ISSUE THREAD

**Issue by GMaxera** [earthly/earthly#1664] opened 2022-02-14 15:58 UTC
I'm trying to run Earthly on WSL2:

```
earthly version v0.6.7 30a39d9b10c429e5a34cdd753652baf9966a3b63 linux/amd64; Ubuntu 20.04
```

but the command fails on detectgit.go: https://github.com/earthly/earthly/blob/7e883a82c30f6d8d530f3f027db489b9d5c9926b/util/gitutil/detectgit.go#L261-L264

```
Error: build target: build main: bkClient.Build: failed to solve: resolve build context for target +build: get rel dir for . when base git path is C:/Users/gianluca.massera/Developer/repos/osirium-main: git base path C:/Users/gianluca.massera/Developer/repos/osirium-main is not absolute
```

because the Git checkout has been performed on Windows 10 using Git for Windows and when earthly run inside WSL2 is not able to detect that and correctly detect the full path of the repository inside WSL2

**Comment by GMaxera** [comment] 2022-02-14 15:59
For these kind of integration WSL2 offer the wslpath utility:
```
osirium_dev@Asset-581:/mnt/c/Users/gianluca.massera/Developer/repos/osirium-main$ wslpath C:/Users/gianluca.massera/Developer/repos/osirium-main
/mnt/c/Users/gianluca.massera/Developer/repos/osirium-main
```

**Comment by brandonSc** [comment] 2022-02-14 19:43
Hi @GMaxera , what command are you running which is failing with those git directory errors? 

I cloned a repo with Git for Windows and then ran some Earthfile targets in that repo from WSL2 and that seemed to work for me.

For example, on Windows I cloned a repo using:
```
git --version
git version 2.33.0.windows.2
```

Then from WSL2 I ran the Earthfile in that repo and it worked. I do have Git also installed on WSL though:
```
git --version
git version 2.25.1
```

I also tried removing `git` from WSL (so I only have it installed for Window) - Earthly gives me a warning `Warning: No git binary found` but actually my target still ran properly.

**Comment by brandonSc** [comment] 2022-02-14 19:45
Potentially related: running my target which I cloned using Git for Windows, from Windows (as opposed to WSL), gives me the following error: 

```
Error: build target: build main: bkClient.Build: failed to solve: resolve build context for target +test: get rel dir for . when base git path is C:/Users/brandon/Documents/Code/earthtest: stat for [C: Users brandon Documents Code earthtest]: CreateFile \C:.: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by GMaxera** [comment] 2022-02-14 21:12
> 
> Then from WSL2 I ran the Earthfile in that repo and it worked. I do have Git also installed on WSL though:
 
I think the culprit is that I heavily use the integrations between WSL2 and Windows 10 and one of those is that you can run Windows 10 .exe inside WSL2, hence the git command I have available inside WSL2 is exactly the Windows 10 executable provided by Git For Windows. So, I don't have installed another Git inside WSL2.

Can you try to see if you can replicate the error I see by removing git inside WSL2 and add in the PATH of WSL2 the Windows 10 git executable?
In my WSL2 setup /usr/local/bin/git is an alias for /mnt/c/PortableGit/bin/git.exe

**Comment by GMaxera** [comment] 2022-02-14 21:17
> 
> Note I also tried removing `git` from WSL (so I only have it installed for Windows) - Earthly gives me a warning `Warning: No git binary found` but actually my target still ran properly.

Thanks for the tip. I'll see if that can be a stopgap for me 👍

**Comment by brandonSc** [comment] 2022-02-15 14:10
> Can you try to see if you can replicate the error I see by removing git inside WSL2 and add in the PATH of WSL2 the Windows 10 git executable?
In my WSL2 setup /usr/local/bin/git is an alias for /mnt/c/PortableGit/bin/git.exe

Will give this a try to see if I can reproduce it.

Nonetheless, I can believe there is a bug here, as that check `filepath.IsAbs(basePath)` will not handle the path prefixed with `C:`.

**Comment by brandonSc** [comment] 2022-02-16 21:12
Still struggling to reproduce this. I've symlinked `/usr/bin/git` to the Windows 10 `.exe` in WSL:
```
❯ which git
/usr/bin/git
❯ git --version
git version 2.33.0.windows.2
```

But actually, my Earthly builds are still succeeding without git errors.

Nonetheless, I think it's more expected that WSL users would run Git for Linux as opposed to the native Windows version. For example, the Microsoft guide for using Git in WSL [suggests this](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git).

**Comment by GMaxera** [comment] 2022-02-16 21:26
> 
> Nonetheless, I think it's more expected that WSL users would run Git for Linux as opposed to the native Windows version. For example, the Microsoft guide for using Git in WSL [suggests this](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git).

I disagree and in any case my current setup doesn't allow me to use Git for Linux inside WSL2.

Anyway, ultimately, for me the ideal solution is to be able to run earthly natively on Windows 10 but that is blocked by https://github.com/earthly/earthly/issues/1663
And it seems to me that issue has more changes to get fixed considering you were able to reproduce.

I will try to see if I can manage to create a WSL2 image that exhibit this issue and export to you.
The culprit point is to make git return a Windows path when running `git rev-parse --show-toplevel` inside WSL2

**Comment by brandonSc** [comment] 2022-02-16 21:49
Sounds good 👍 - I think #1663 is the more pressing issue as well, so I'm looking into a fix for that one currently.

**Comment by brandonSc** [comment] 2022-02-16 21:54
By the way, I've managed to get the error when using Git for Windows in WSL now as well, will see if I can scoop in a fix for that while I'm at it.

**Comment by GMaxera** [comment] 2022-02-17 17:17
https://github.com/earthly/earthly/pull/1681 will make this one gone away automatically, because once fixed the various issue to run Earthly natively on Windows, there will be no need of this special hybrid case to be supported.

**Comment by brandonSc** [comment] 2022-03-03 01:49
Since #1663 is fixed, I think we can close this one.

**Closed** 2022-03-04 16:09 UTC
Labels: type:bug
