### ISSUE TITLE
Passing secrets to FROM DOCKERFILE builds

### ISSUE THREAD

**Issue by dustyhorizon** [earthly/earthly#2513] opened 2022-12-18 19:44 UTC
Hello,

I am currently exploring earthly as a replacement for my aging Makefiles but would like to ask if its possible to pass in secrets used by [RUN](https://docs.docker.com/engine/reference/builder/#run---mounttypesecret) commands in Dockerfiles via earthly cli?

Currently these Dockerfiles are consumed by the FROM DOCKERFILE command in the Earthfile.

I have tried variations of [passing in secrets](https://docs.earthly.dev/docs/guides/build-args#passing-secrets-to-run-commands) but to no avail. Specifically, earthly reports `Error: build target: build main: failed to solve: name parameter not found`

For more context, these Dockerfiles were previously built via `docker build --secret id=xxx,env=xxx ...`

IF it is not currently supported, maybe the `--secret` flag should be introduced to the `FROM DOCKERFILE` command in similar vein to `--build-arg`?

**Comment by alexcb** [comment] 2022-12-30 20:52
This is a duplicate of #1483, please give it a :+1: to help us prioritise it.

**Closed by alexcb** 2022-12-30 20:52 UTC
