### ISSUE TITLE
how can i load local image 

### ISSUE THREAD

**Issue by rmGFW** [earthly/earthly#3990] opened 2024-04-05 03:14 UTC
VERSION 0.8
FROM local-image

build:
   ....

---
i want use local image ,but it will pull the local-image then failed

**Comment by Nasfame** [comment] 2024-04-06 07:32
If u do have dockerfile: then do:

```
dockerfile:
  FROM DOCKERFILE .
  SAVE IMAGE hive:dockerfile
```

If not possible, try to create a dockerfile with the local image specified 

```
FROM local-image
```

I presume this should work in ur system:

```
VERSION 0.8
FROM local-image
```

But make sure u do : `earthly --no-sat +[recipeName]`

**Comment by Nasfame** [comment] 2024-04-09 22:13
I think its more consistent to use a dockerfile.

**Comment by alexcb** [comment] 2024-04-09 22:18
duplicate of #1412

**Closed by alexcb** 2024-04-09 22:18 UTC
Labels: type:proposal
