### ISSUE TITLE
Error when using explicit shared cache and `cache-hint` targets

### ISSUE THREAD

**Issue by mortenlj** [earthly/earthly#1604] opened 2022-01-22 21:54 UTC
I get an error when trying to use `SAVE IMAGE --cache-hint` while doing a `--push`.

Earthly version: 0.6.4
OS: Linux / Ubuntu 21.10

Minimal example:

```earthly
VERSION 0.6

FROM busybox

target1:
    SAVE ARTIFACT /no-file
    SAVE IMAGE --cache-hint

target2:
    SAVE ARTIFACT /no-file
    SAVE IMAGE --cache-hint

docker:
    COPY +target1/ .
    COPY +target2/ .
    SAVE IMAGE --push test_image:latest
```

When built with `earthly --push --remote-cache=test_image:cache +docker`, this fails:
```
Error: build target: build main: bkClient.Build: failed to solve: image  is defined multiple times for the same default platform
```

**Comment by vladaionescu** [comment] 2022-01-22 22:11
Hi @mortenlj - this is actually a duplicate of https://github.com/earthly/earthly/issues/1594. The fix will be out in the next release.

**Closed by vladaionescu** 2022-01-22 22:11 UTC
Labels: type:bug
