### ISSUE TITLE
build command calls to api.earthly.dev when not needed

### ISSUE THREAD

**Issue by wburningham** [earthly/earthly#2954] opened 2023-05-16 16:08 UTC
When running a simple target that runs `echo "foo"` the build command attempts to setup/detect a cloud-based auth provider by making calls to `https://api.earthly.dev/api/v0/account/auth-challenge`. For my use case we don't want/need any calls to https://api.earthly.dev/.

Is there a way to set a value in the earthly config to explicitly skip trying to setup a cloud-based auth provider?

Context:

- [Slack discussion here](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1684252800254259)

**Comment by alexcb** [comment] 2023-06-16 20:40
#3034 implements a fix for this, which will prevent auto login after a call to `earthly account logout`, or by `touch ~/.earthly/do-not-login-automatically`

**Comment by alexcb** [comment] 2023-06-16 20:46
duplicate of #2827

**Closed by alexcb** 2023-06-16 20:46 UTC
