### ISSUE TITLE
Different behavior from local and remote targets with save artifact

### ISSUE THREAD

**Issue by diegobernardes** [earthly/earthly#820] opened 2021-02-26 01:23 UTC
I'm having some problems with saving artifacts using remote targets. I can't post the whole target code, but it looks like this:
```
generate:
  ARG NAME
  ARG TEAM
  ARG OUTPUT_DIR
  FROM +cookiecutter
  COPY . .
  ...
  SAVE ARTIFACT $NAME AS LOCAL $OUTPUT_DIR/$NAME
```

If I run this locally it will generate the files at the target and then output them to my local filesystem, which is what we expect. But, if I run the same target remotely it does everything as expected but does not output the files.

This is the last section of the remote execution:
```
g/o/repo:main+generate | NAME=my-app OUTPUT_DIR=/tmp/ TEAM=xyz
g/o/repo:main+generate | *cached* --> RUN ...
              output | --> exporting outputs
              output | [██████████] sending tarballs ... 100%
=================================== SUCCESS ====================================
```

**Comment by vladaionescu** [comment] 2021-02-26 01:40
Hi @diegobernardes - this is working as intended. Remote targets don't create local files because earthly wouldn't know where to put them exactly. The `AS LOCAL` location is relative to the Earthfile of that target. So if it's a remote target, then that dir doesn't really exist on the host system.

What you can do is either use artifact mode `earthly --artifact github.com/foo/bar:main+generate/my/file ./out` or, if you'd like this to be integrated with the Earthfile that is using it, do

```
COPY +gihub.com/foo/bar:main+generate/my/file ./out
SAVE ARTIFACT ./out AS LOCAL ./out
```

Closing this as working as intended - but feel free to ask more questions.

I'm curious if this is enough for your use-case or you have another reason why you'd like a remote target to output local files directly.

**Closed by vladaionescu** 2021-02-26 01:40 UTC
Labels: resolution:wontfix

**Comment by diegobernardes** [comment] 2021-02-26 10:54
> Hi @diegobernardes - this is working as intended. Remote targets don't create local files because earthly wouldn't know where to put them exactly. The AS LOCAL location is relative to the Earthfile of that target. So if it's a remote target, then that dir doesn't really exist on the host system.

I didn't know about that, thanks for clarifying. Thinking about the remote execution I think it would be safe to assume that the root location would be the execution path at the filesystem. Maybe accept a `--workdir` at the CLI like the `-f` at Docker?

> What you can do is either use artifact mode earthly --artifact github.com/foo/bar:main+generate/my/file ./out or, if you'd like this to be integrated with the Earthfile that is using it, do
>
> COPY +gihub.com/foo/bar:main+generate/my/file ./out
SAVE ARTIFACT ./out AS LOCAL ./out

The problem with this approach is that I would have to create two targets, one for local execution and one for remote execution. Because my current target looks like this:
```
generate:
  ARG NAME
  ARG TEAM
  ARG OUTPUT_DIR
  FROM +cookiecutter
  ...  
  SAVE ARTIFACT $NAME AS LOCAL $OUTPUT_DIR/$NAME
```

I tried the remote target execution with the `--artifact` and I'm getting some errors, could this be caused by the fact that the target has the `AS LOCAL`?

```
➜ earthly --build-arg NAME="app" --build-arg TEAM="xyz" --build-arg OUTPUT_DIR="." --artifact github.com/org/repo:main+generate/app /tmp/app
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
Error: build target: mk temp dir for artifacts: mkdir .tmp-earthly-out031898595: no such file or directory
```

> Closing this as working as intended - but feel free to ask more questions.
> 
> I'm curious if this is enough for your use-case or you have another reason why you'd like a remote target to output local files directly.

Thank you for the amazing work you've been done with Earthly. Over the years I've been doing Earthly like Makefiles but it was always felt like a hack. Earthly fits perfect my needs.

I'm introducing Earthly at the company that I work for and most of my projects here are already migrated to it. I'm also trying to introduce Earthly as a remote task runner. For example, I have a repository that it's a template used by [cookiecutter](https://github.com/cookiecutter/cookiecutter) to create new Go services. The idea is that instead of forcing the developer to clone the repository to execute Earthly locally I would simply add a note at the readme to execute Earthly remotely.

**Comment by vladaionescu** [comment] 2021-02-26 18:20
Ah interesting. If this is a template, we also have an ongoing proposal that may be of some help. Wonder if it might be useful to you in some way: https://github.com/earthly/earthly/issues/581

I think your suggestions could make sense in conjunction with a rework of how to decide whether something is output or not. I'll need to put up a proposal with that.

In the meantime, I think that `--artifact` could help bridge the gap.

Re: `no such file or directory` error

I think that the earthly command was run from a directory where earthly doesn't have permission to create a temporary dir. The command looks good otherwise, as far as I can tell. If that's not the case, could you also try `./app` as the dest path?

Let me know if this works - if not it could be an important bug to fix.

**Comment by diegobernardes** [comment] 2021-02-27 21:16
I did figure out the problem and it was the way that I was executing the command, it's solved now. No problem with earthly 👍🏻 

Yes, #581 will help to make the execution command simpler. It's also good to be able to share common things like how to execute tests, build, deploy, etc.. for sure I'll use it.

One idea to that proposal is to introduce an especial ARG like for example `ARGS`, the name is awful and I can't think on something better 😅, if that argument is present it would map everything after the target at the command line. Example:

```
list:
  ARG ARGS
  RUN ls $ARGS
```

```
earthly +list -la
```

With this feature earthly can be used as a sandbox shell and it can make it easier to expose apps. It's the same thing as docker entrypoint.
