### ISSUE TITLE
Secrets in .env may be output to build logs

### ISSUE THREAD

**Issue by tibbes** [earthly/earthly#2336] opened 2022-11-01 12:12 UTC
The documentation for earthly says that one way of [providing secrets](https://docs.earthly.dev/docs/guides/build-args#setting-secret-values) is to place them a file called `.env`. However, some errors can cause these values to appear in the output of earthly, which means they may be saved to CI logs or similar insecure locations.

### How to reproduce

Create a secret in an `.env` file.

```
netrc=machine goproxy.githubapp.com login nobody password DO-NOT-REVEAL-THIS
```

Create an `Earthfile` with an unsupported flag to a built-in command:

```Earthfile
VERSION 0.6

test:
    FROM bash:latest
    RUN --mount type=secret,target=/root/.netrc,id=+secrets/netrc \
        cat /root/.netrc > /dev/null
    RUN --nonsense
```

Run earthly

```
$ earthly +test
 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

         bash:latest | --> Load metadata linux/amd64
unknown flag `nonsense'

<...snipped...>
Error: build target: build main: failed to solve: Earthfile line 7:4 invalid RUN arguments [--nonsense]: unknown flag `nonsense'
in		github.com/github/transitions/repro:order-stamps+test --netrc=machine goproxy.githubapp.com login nobody password DO-NOT-REVEAL-THIS
```

### Potential fixes

Some potential fixes (more than one could be done) are:
1. Update the documentation to no longer recommend putting secrets in `.env`
2. Add support for a different file just for secrets (e.g. `.secrets`)
3. No longer allow loading secrets from `.env` (could break existing builds)

**Comment by alexcb** [comment] 2022-11-01 16:41
duplicate of #2336

(I will move the suggested fixes there)

**Closed by alexcb** 2022-11-01 16:41 UTC
