### ISSUE TITLE
`WITH DOCKER` cgroup changes in `0.7.14` breaks builds

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#3201] opened 2023-08-22 02:40 UTC
**What went wrong?**

An existing project that spins up a [kind](https://kind.sigs.k8s.io/) cluster inside `WITH DOCKER` no longer works in `0.7.14` or `0.7.15`.

This can be replicated fairly simply:
```Earthfile
VERSION 0.7

repro:
    FROM earthly/dind:alpine-3.18
    RUN wget -O /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64 && \
        chmod +x /usr/local/bin/kind
    WITH DOCKER --load kind=+kind-image
        RUN kind create cluster -v1 --image kind --retain; ret=$?; \
            echo "=== Docker ==="; \
            grep 'level=error' /var/log/docker.log; \
            echo "=== Kind ==="; \
            docker logs kind-control-plane 2>&1 | grep Failed; \
            exit $ret
    END

kind-image:
    # Reason for this trivial level of indirection: https://github.com/earthly/earthly/issues/1852
    FROM kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
    SAVE IMAGE kind
```

The two newest versions of earthly fail in the same way:
```
$ earthly --version
earthly version v0.7.15 ae8f65528ad37a278985de2e234deb42b91e308f linux/amd64; Ubuntu 22.04.2 LTS (Jammy Jellyfish)

$ earthly --no-cache -P +repro 
 <snip>
              +repro | Creating cluster "kind" ...
              +repro |  • Ensuring node image (kind) 🖼  ...
              +repro | DEBUG: docker/images.go:58] Image: kind present locally
              +repro |  ✓ Ensuring node image (kind) 🖼
              +repro |  • Preparing nodes 📦   ...
              +repro |  ✗ Preparing nodes 📦 
              +repro | ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"

              +repro | Stack Trace: 
              +repro | sigs.k8s.io/kind/pkg/errors.Errorf
              +repro | 	sigs.k8s.io/kind/pkg/errors/errors.go:41
              +repro | sigs.k8s.io/kind/pkg/cluster/internal/providers/common.WaitUntilLogRegexpMatches
              +repro | 	sigs.k8s.io/kind/pkg/cluster/internal/providers/common/cgroups.go:84
              +repro | sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.createContainerWithWaitUntilSystemdReachesMultiUserSystem
              +repro | 	sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go:407
              +repro | sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.planCreation.func2
              +repro | 	sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go:115
              +repro | sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
              +repro | 	sigs.k8s.io/kind/pkg/errors/concurrent.go:30
              +repro | runtime.goexit
              +repro | 	runtime/asm_amd64.s:1581
              +repro | === Docker ===
              +repro | time="2023-08-22T01:40:01.587196814Z" level=error msg="Could not add route to IPv6 network fc00:f853:ccd:e793::1/64 via device br-a1ee8ea255a9: network is down"
              +repro | time="2023-08-22T01:40:04.735602912Z" level=error msg="failed to enable controllers ([cpuset cpu io memory hugetlb pids rdma misc])" error="failed to write subtree controllers [cpuset cpu io memory hugetlb pids rdma misc] to \"/sys/fs/cgroup/docker/cgroup.subtree_control\": write /sys/fs/cgroup/docker/cgroup.subtree_control: no such file or directory"
              +repro | === Kind ===
              +repro | Failed to create /init.scope control group: Operation not supported
              +repro | Failed to allocate manager object: Operation not supported
              +repro | [!!!!!!] Failed to allocate manager object.
              +repro | ERROR Earthfile line 9:8
              +repro |       The command
              +repro |           WITH DOCKER RUN --privileged kind create cluster -v1 --image kind --retain; ret=$?; echo "=== Docker ==="; grep 'level=error' /var/log/docker.log; echo "=== Kind ==="; docker logs kind-control-plane 2>&1 | grep Failed; exit $ret
              +repro |       did not complete successfully. Exit code 1
              output | [----------] 100% transferring docker.io/library/kind:latest

============================= ❌ FAILURE [Build 🔧] ==============================
```
1. I'm assuming (but don't know for sure) that the "failed to write subtree controllers" from the docker daemon is directly responsible for the "failed to create control group" from kind container.
2. The user-facing kind error mentions v1, but that's a distraction; when things are working, the first condition ("multi-user system") matches.

Running with an older buildkit (even with newest client) works fine:
```
$ earthly --buildkit-image docker.io/earthly/buildkitd:v0.7.13 --no-cache -P +repro 
<snip>
              +repro | Creating cluster "kind" ...
              +repro |  • Ensuring node image (kind) 🖼  ...
              +repro | DEBUG: docker/images.go:58] Image: kind present locally
              +repro |  ✓ Ensuring node image (kind) 🖼
              +repro |  • Preparing nodes 📦   ...
              +repro |  ✓ Preparing nodes 📦 
              +repro |  • Writing configuration 📜  ...
              +repro |  ✓ Writing configuration 📜
              +repro |  • Starting control-plane 🕹️  ...
             ongoing | output (23 seconds ago), +repro (20 seconds ago)
              +repro |  ✓ Starting control-plane 🕹️
              +repro |  • Installing CNI 🔌  ...
              +repro |  ✓ Installing CNI 🔌
              +repro |  • Installing StorageClass 💾  ...
              +repro |  ✓ Installing StorageClass 💾
              +repro | Set kubectl context to "kind-kind"
              +repro | You can now use your cluster with:

              +repro | kubectl cluster-info --context kind-kind

              +repro | Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
              +repro | === Docker ===
              +repro | time="2023-08-22T01:44:57.534930990Z" level=error msg="Could not add route to IPv6 network fc00:f853:ccd:e793::1/64 via device br-cc98e3df39ce: network is down"
              +repro | === Kind ===
             ongoing | output (33 seconds ago), +repro (31 seconds ago)
              output | [----------] 100% transferring docker.io/library/kind:latest
              output | --> exporting outputs
<snip>
========================== 🌍 Earthly Build  ✅ SUCCESS ==========================
```

**What should have happened?**

The expected outcome is that the behavior (success) remain consistent between versions.

The only workaround I've found is using a `0.7.13` or older buildkit.

**Other Helpful Information**

Notes:
1. That is a relatively old kind version, but is the exact version that stopped working.  I do not believe the version is relevant, as I tried upgrading it during the debug process, with no effect (despite recent versions dealing with cgroups)
3. The earthly versions in question also correspond to the alpine/docker versions in the 'dind' image; I am pretty confident that is not a factor.
4. I took the existing `0.7.15` buildkit image and swapped in a `0.7.13` entrypoint, both as a diagnostic step and a long-shot for a fix; it made no difference, which suggests upstream buildkit is the cause (or contributor)
5. Based on previous experiences with errors like these, this feels like a cgroup namespace thing (private vs. host).  If I had the time to track this down further, I'd probably start in the neighborhood of https://github.com/earthly/buildkit/pull/21/commits/c96364913ef6fed024604ff6ec1b0aa445dec53e (which was added between `0.7.13` and `0.7.14`).

**Comment by rrjjvv** [comment] 2023-08-22 04:43
I was definitely not expecting this to work, but... it did.  I simply reverted the above commit, and the build works:
```
$ git log earthly-main..rev
commit f540291550d55324edd08766085f2b47ecd1266a (HEAD -> rev, origin/rev)
Author: Roberto Villarreal <robertovillarreal@overstock.com>
Date:   Mon Aug 21 21:24:38 2023 -0600

    Revert "oci: make sure cgroupns is enabled if supported"
    
    This reverts commit c96364913ef6fed024604ff6ec1b0aa445dec53e

$ earthly github.com/earthly/earthly/buildkitd:v0.7.15+buildkitd --BUILDKIT_PROJECT=github.com/rrjjvv/buildkit:rev
<snip>
Image github.com/earthly/earthly/buildkitd:v0.7.15+buildkitd output as docker.io/earthly/buildkitd:dev-v0.7.15

$ earthly --buildkit-image docker.io/earthly/buildkitd:dev-v0.7.15 -P +test
<snip glorious success output>
```

I'm sure that commit was supposed to be a "feature", so a revert is not the (ideal) fix.  I haven't actually looked at the code paths involved, but I'm guessing this change is effectively 'advertising' its knowledge/capability to use cgroup namespaces, which in turn changes the defaults/fallbacks that other tools (inner docker and/or kind) use in response.

P.S.  I'll never get over how awesome it is that I can execute the earthly command that I did... being able to execute 'your' remote target, and tell it to use 'my' remote target during its build!

**Comment by alexcb** [comment] 2023-08-23 16:38
duplicate of #3159

Reverting that commit may cause issues if you try to run earthly-in-earthly, as v0.7.14 removed some changes to the `entrypoint.sh`, which were no longer needed due to the cgroupns being set via buildkit.

I'm actively working on this issue (but tracking via the original ticket).

**Closed by alexcb** 2023-08-23 16:38 UTC
Labels: type:bug

**Comment by rrjjvv** [comment] 2023-08-23 17:40
Dang, I don't know how I didn't see it; sorry!
