### ISSUE TITLE
Native Windows Installation?

### ISSUE THREAD

**Issue by zdog234** [earthly/earthly#941] opened 2021-04-23 15:13 UTC
Hi, based on #864 , I'm guessing that this is already in your backlog, but I just wanted to check:

Are there plans for a native windows installation?

More and more people in my org are switching to either WSL 2 or MacOS, but there are still a decent number of people who are still just on windows.

Thanks :)

**Comment by vladaionescu** [comment] 2021-04-24 00:00
Yes - it's on the backburner. @dchw is working on that as a side pet project. Thanks for being patient with us, we had tons of requests lately.

Duplicate of #544

**Closed by vladaionescu** 2021-04-24 00:00 UTC
