### ISSUE TITLE
Does no-login user should to visit  https://api.earthly.dev/api/v0/account/auth-challenge ?

### ISSUE THREAD

**Issue by cupen** [earthly/earthly#2940] opened 2023-05-11 07:31 UTC
* os: archlinux
* version: 0.7.5  (installation follow https://earthly.dev/get-earthly)

It happens occasionally. I know it's my network jetter, but I'm a no-login user, maybe there isn't need to visit that url, so it's a  bug, right? If yes, I'll try to fix it.
```
earthly +build-env2

 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
retrying http request due to unexpected error Get "https://api.earthly.dev/api/v0/account/auth-challenge": dial tcp: lookup api.earthly.dev: i/o timeout {reqID: ---}
retrying http request due to unexpected error Get "https://api.earthly.dev/api/v0/account/auth-challenge": dial tcp: lookup api.earthly.dev: i/o timeout {reqID: ---}
retrying http request due to unexpected error Get "https://api.earthly.dev/api/v0/account/auth-challenge": dial tcp: lookup api.earthly.dev: i/o timeout {reqID: ---}
```

My network is under China GFW, it feels like using a telephone line from the last century. Sorry for that.

**Comment by alexcb** [comment] 2023-06-12 21:00
as a work around until this is fixed, you can run:

```
SSH_AUTH_SOCK="" earthly +build-env2
```

**Comment by alexcb** [comment] 2023-06-16 20:42
#3034 implements a fix for this.

Once it's released a user can run `earthly account logout`, or `touch ~/.earthly/do-not-login-automatically` which will disable the auto-login functionality.

**Comment by alexcb** [comment] 2023-06-16 20:46
duplicate of #2827

**Closed by alexcb** 2023-06-16 20:46 UTC
