### ISSUE TITLE
failed to get edge: inconsistent graph state

### ISSUE THREAD

**Issue by immesys** [earthly/earthly#3506] opened 2023-11-17 10:22 UTC
**What went wrong?**
In our builds, we frequently get the error: 

```
_unknown *failed* | build target: build main: failed to solve: async force execution for +test: unlazy force execution: failed to get edge: inconsistent graph state
```

It's not just the test target, it's a fair number of the other ones

I don't have an isolated earthfile that showcases the problem, but the problem arose when we started using ARG in our earthfiles and started building multiple platforms. E.g. one of the rules has this, which might be causing the issue:

```
test-itg:
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
    # run docker-compose inside the block because earthly's built-in compose flag doesn't support wait
    WITH DOCKER \
            --load dev-postgres:latest=+img-postgres \
            --load cell:latest=(+img-cell --IMAGE_TAG=dev --COVERAGE=true) \
            --load global:latest=(+img-global --IMAGE_TAG=dev --COVERAGE=true)
        RUN --no-cache \
             docker-compose -f compose.yaml --profile no-web up --wait && \
             our_integration_test.sh
    END
```

so there could be multiple versions of `+img-cell` being depended on, with different tags and potentially different platforms.

This target often causes errors as well:

```
bins:
   BUILD --platform linux/amd64 +celld
   BUILD --platform linux/arm64 +celld

   BUILD --platform linux/amd64 +globald
   BUILD --platform linux/arm64 +globald

# globald looks the same
 celld: 
    FROM +generate
    ARG TARGETOS
    ARG TARGETARCH
    ARG COVERAGE=false
    IF [ "$COVERAGE" == "true" ]
        RUN go build -o output/celld --cover <ourprogram>
    ELSE
        RUN go build -o output/celld <ourprogram>
    END
    SAVE ARTIFACT output/celld
    SAVE ARTIFACT output/celld AS LOCAL build/celld-$TARGETOS-$TARGETARCH
```
    
If you have an idea of what might be causing it, I can try make a reproducing earthfile

**What should have happened?**
I don't expect to see this error

As a workaround, running it again often works the second time. Sometimes running prune helps for a little bit.

**Other Helpful Information**

```
earthly version v0.7.21 f4c9f47e48c3815e95fe9574e824524d34a20219 darwin/arm64; macOS 13.3.1 homebrew

```

**Comment by alexcb** [comment] 2023-11-17 17:24
duplicate of #2454

**Closed by alexcb** 2023-11-17 17:24 UTC
Labels: type:bug
