### ISSUE TITLE
Escape `#` character in Earthfile

### ISSUE THREAD

**Issue by jchorl** [earthly/earthly#3360] opened 2023-10-09 15:13 UTC
**What went wrong?**
I'm trying to use a literal `#` char in an Earthfile. Consider the following:
```
VERSION 0.7

docker:
    FROM alpine:3.18
    RUN echo foo > my_file.txt
    RUN sed -i'' s/foo/'bar # HACK: baz'/ my_file.txt
    SAVE IMAGE jchorl/earthly-test:tmp-123
```

Running it produces:
```
/workspace/tmp+docker | /bin/sh: syntax error: unterminated quoted string
/workspace/tmp+docker | ERROR /workspace/tmp/Earthfile line 6:4
/workspace/tmp+docker |       The command
/workspace/tmp+docker |           RUN sed -i'' s/foo/'bar
/workspace/tmp+docker |       did not complete successfully. Exit code 2
```

Other variants I tried:
```
    RUN sed -i'' s/foo/'bar ## HACK: baz'/ my_file.txt
```

```
    RUN sed -i'' s/foo/'bar \# HACK: baz'/ my_file.txt
```

Note that the following Dockerfile _does_ work:
```dockerfile
FROM alpine:3.18
RUN echo foo > my_file.txt
RUN sed -i'' s/foo/'bar \# HACK: baz'/ my_file.txt
```

```
docker build -t jchorl/test .
docker run -it --rm jchorl/test sh
/ # cat my_file.txt 
bar # HACK: baz
```

**What should have happened?**
I'd expect there to be a way to use a literal `#` char in a command

Really, 2 asks here:
1. Is this possible with any incantation today?
2. I actually couldn't find docs on comments in Earthfiles. It seems silly, and was intuitive to me until I hit this case. Perhaps comments (and reserved/special chars, and escaping those reserved/special chars) should be documented?

**Comment by alexcb** [comment] 2023-10-10 16:27
duplicate of #3131 and #1280; you might have better luck using double-quotes.

I'll open a separate issue to improve our docs on comments -- it's a good point.

**Closed by alexcb** 2023-10-10 16:27 UTC
Labels: type:bug
